repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
    - id: debug-statements
    - id: check-merge-conflict
    - id: trailing-whitespace
      args: ['--markdown-linebreak-ext=md']
    - id: check-executables-have-shebangs
    - id: check-ast
    - id: check-byte-order-marker
    - id: check-json
    - id: check-symlinks
    - id: check-vcs-permalinks
    - id: check-xml
    - id: check-yaml
    - id: detect-private-key
    - id: forbid-new-submodules
    - id: no-commit-to-branch
      args: ['-b master']

-   repo: https://github.com/timothycrosley/isort
    rev: 5.2.0
    hooks:
    - id: isort
      args: ['--diff']

-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.3
    hooks:
    - id: flake8
      args: ['--exclude=docs/*', '--ignore=E501']

-   repo: local
    hooks:

    - id: check-datetime-now
      name: check_datetime_now
      description: Prefer datetime.utcnow()
      language: pygrep
      entry: 'datetime\.now\(\)'
      types: [python]

-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.3.0
    hooks:
    - id: python-check-mock-methods
      args: []

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: ''  # Use the sha / tag you want to point at
    hooks:
    -   id: mypy
        args: [--no-strict-optional, --ignore-missing-imports]
        additional_dependencies: [tokenize-rt==3.2.0]