[tool.poetry]
name = "vm-trainer"
version = "1.0.0"
description = "a qemu manager for gpu passthrough"
authors = ["Rodrigo Antonio de Araujo <rodjjo@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
click = "^8.1.7"
pyaml = "^25.1.0"
pyyaml  = "^6.0.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.package]
include = [
     { path =  "vm_trainer/bios", format = "dir" }
]

[tool.poetry.scripts]
vm-trainer = "vm_trainer.cli:main"